# Generated by Django 5.2.12 on 2026-05-22 05:04

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.CharField(default=apps.users.models.generate_id, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('created_post', 'Created Post'), ('liked_post', 'Liked Post'), ('saved_post', 'Saved Post'), ('followed_user', 'Followed User'), ('commented_post', 'Commented Post'), ('shared_post', 'Shared Post')], max_length=50)),
                ('reference_type', models.CharField(max_length=50)),
                ('reference_id', models.CharField(max_length=26)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.CharField(default=apps.users.models.generate_id, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('suspend_user', 'Suspend User'), ('ban_user', 'Ban User'), ('activate_user', 'Activate User'), ('hide_post', 'Hide Post'), ('delete_post', 'Delete Post'), ('delete_comment', 'Delete Comment'), ('resolve_report', 'Resolve Report'), ('update_system_setting', 'Update System Setting')], max_length=50)),
                ('target_type', models.CharField(choices=[('user', 'User'), ('post', 'Post'), ('comment', 'Comment'), ('report', 'Report'), ('system', 'System')], max_length=20)),
                ('target_id', models.CharField(blank=True, max_length=26, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.CharField(default=apps.users.models.generate_id, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
